apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag
      version: v2
  template:
    metadata:
      labels:
        app: rag
        version: v2
    spec:
      serviceAccountName: rag
      containers:
      - name: rag
        image: linsun/rag:v2  # You'll need to build and push this image to your registry
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: OLLAMA_BASE_URL
            value: "http://host.docker.internal:11434"
            # value: "http://ollama.ollama:80"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rag
# spec:
#   selector:
#     app: rag
#   ports:
#   - port: 80
#     targetPort: 8000
#     name: http
# ---
apiVersion: v1
kind: Service
metadata:
  name: rag-v2
spec:
  selector:
    app: rag
    version: v2
  ports:
  - port: 80
    targetPort: 8000
    name: http